site_name: Custom Recipes Wiki
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - Command Usage: command-usage.md
  - Other:
    - Future Ideas: ideas.md
    - Credits: credits.md
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
