site_name: Custom Recipes Wiki
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - Command Usage: command-usage.md
  - FAQ: faq.md
  - Recipes:
    - Crafting:
    - Smelting:
    - Blasting:
  - Other:
    - Change Log: changes.md
    - Future Ideas: ideas.md
    - Credits: credits.md
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
